### ISSUE TITLE
[Req] watchlist intergration 

### ISSUE THREAD

**Issue by b1n4ryk1lla** [DxCx/plugin.video.9anime#223] opened 2018-04-24 20:17 UTC
Would be cool if like on the website we can use the watchlist to pull up what we are 
planning on watching and know where you left off at (trakt intergration would work too) but the site already has this

**Comment by HatHeadNinja** [comment] 2018-04-25 02:16
Can you use "Add to Favorites" for this, and then your Favorites is your watch list? That's what I do: I add a favorite at the season level. Then, for each episode, Kodi already puts an indicator for Unwatched, Watched and In-Progress by each title...and if you select an in-progress title, Kodi asks you if you want to start where you left off or from the beginning again.  Is this the kind of thing you mean?

**Comment by b1n4ryk1lla** [comment] 2018-04-25 02:55
You could but it defeats the purpose of 9anime tracking ie I have a list already of what I plan to watch and how far I'm into it already on the site many I don't not remember the name of until I find the list

**Comment by b1n4ryk1lla** [comment] 2018-04-25 02:59
Ie

https://www4.9anime.is/user/339717/watchlist

**Comment by HatHeadNinja** [comment] 2018-04-25 03:28
Gotcha! Makes sense then! (I don't use the site at all, only to check when there's a problem.)

**Comment by DxCx** [comment] 2018-04-25 18:54
Duplicate of #23

**Closed by DxCx** 2018-04-25 18:54 UTC
