### ISSUE TITLE
LibreELEC Krypton ERROR: EXCEPTION Thrown (PythonToCppException)

### ISSUE THREAD

**Issue by justin89h** [DxCx/plugin.video.9anime#35] opened 2017-05-19 07:31 UTC
Great plugin :) I really appreciate the work you've put into maintaining this. So many other streaming anime plugins have been failing lately. 

I have the latest version of your plugin installed on LibreELEC on the RaspberryPi 3 Model B. I have started receiving a couple occasional errors since the TokenDecoder update.

1. The plugin fails to load, and has to be restarted (The error shown in the title). Full logs of this error here: [Logs.txt](https://github.com/DxCx/plugin.video.9anime/files/1013413/Logs.txt)

2. I don't have a log file for this as I can't get it to consistently appear, but occasionally when trying to play an episode it displays an error with no sources available. When I immediately try again, it succeeds with no problems.

**Details:**

I have 3 custom widgets I added into the default Estuary skin. One showing the menu options of the plugin, one accessing the 'Latest' anime, and another on the same page showing Kodi's favourites. (labelled 'Currently Watching')

I can (somewhat) consistently make the first error appear by clicking a favourite directed to an anime's episode listing from the plugin **before**  the latest anime and menu options widgets have finished loading. 

I understand this is an isolated case, but as its logged to be potentially a memory leak error and may occur in other situations, it might be worth putting a priority on investigating anyway.

I have taken a quick photo of the widgets displayed on the TV: 

![9anime](https://cloud.githubusercontent.com/assets/28800851/26237356/f9f36e7a-3cb3-11e7-961a-900b1d73b954.jpg)

**Comment by DxCx** [comment] 2017-05-20 05:20
hey @justin89h,

The issues you are seeing indeed related to Token thingy,
the decoding algorithm has some usecase that it's not handling right,
however, since it do work 90% of the times, i decided to release it to let people enjoy the anime,

if the first issue mentioned is really caused by the error in the log then it's the same issue happens to you on 2ed bullet.

regarding memory leak mentioned above, this is a generic message comes with exceptions..  

i wanted to fix this properly but did not have the time for that yet..

**Comment by justin89h** [comment] 2017-05-20 05:41
Hey, thanks for the quick reply. If you already know about it that's great :) Hopefully the info I provided will assist a little when you get time to fix it. 

Definitely the right call to release it early as it works 90% of the time. Thanks. :)

**Comment by githubus11** [comment] 2017-05-20 09:53
added unicode_support for tokens so it shouldnt fail because of tokens anymore

another non token related issue is, that crawling of f1 und f2 urls is sometimes too fast and the server will respond with 503 and some silly text. tried forced delays and retries in my code but it didnt work reliably.

**Comment by rbz205** [comment] 2017-05-20 15:53
@justin89h How did you get the "Anime" Left menu option? That looks pretty cool. Thanks in advance.

**Comment by justin89h** [comment] 2017-05-20 16:16
@githubus11 Sounds good, thanks heaps for working on it :) It's great that you're helping with this plugin. I'll use the new version over the next couple days and let you know if all goes well

@rbz205 I modified the original Estuary files pretty heavily but you can achieve a similar look a lot easier with use of Estuary Mod: forum.kodi.tv/showthread.php?tid=267343
If you'd rather modify Estuary yourself let me know and I'll upload the files I modified and you can have a look.

**Comment by githubus11** [comment] 2017-05-20 20:03
Hi,

played with the Estuary mod and got token parsing errors even after last fix. looked into it and found it. made a pullrequest. the next time it fails, youll see the complete token in kodi.log which you can post in here for debug purpose

**Comment by DxCx** [comment] 2017-05-20 20:57
Alright @justin89h, @githubus11's patch just got merged, can you please give it a try by downloading the zip again and install it over?

**Comment by justin89h** [comment] 2017-05-21 02:01
Alright, tried my best to break it for half an hour this morning with no success, so all looks good at this stage. Good work! We can close this issue now if you like and I'll open up a new one if errors appear again

**Comment by DxCx** [comment] 2017-05-24 08:18
cool thanks @justin89h for reporting back and @githubus11 for fixing =)

**Closed by DxCx** 2017-05-24 08:18 UTC
