### ISSUE TITLE
9anime update please help

### ISSUE THREAD

**Issue by grabberboy** [DxCx/plugin.video.9anime#152] opened 2017-11-25 10:01 UTC
i was worried no source are available
until i look on 9anime
there are new on their system
https://9anime.is/ajax/episode/info?ts=1511600400&_=2667&id=4vpz3o&server=22&update=0

the Token and options are now encoded on something
and maybe from all.js can decrypt the token and options for the grabber url 

please help someone loook on this

**Comment by grabberboy** [comment] 2017-11-25 11:24
@hoppler 
@DxCx 
@

**Comment by hoppler** [comment] 2017-11-25 18:57
the encryption is rot_8. @DxCx id be glad if you could remove donations from this repo as im doing this not for the money. please keep in mind that this plugin is not that legal

**Comment by DxCx** [comment] 2017-11-25 20:45
Thanks for the report @grabberboy i'll take a look at that when i have time, hopefuly in the next few days. and thanks for the tip @hoppler :D

Im not doing this for money as well,
also no one ever donated a penny yet.
the donations is just for those who want to support and cannot do it with pull requests...
about legal, this is just a browser addon, it does not do anything else then simple http browsing..

**Comment by grabberboy** [comment] 2017-11-26 04:59
new update again from 9anime
the Ts is now Encrypted too
anyone knows the encription method?

**Comment by DxCx** [comment] 2017-11-26 06:38
duplicate of #151 let's move discussion there.

**Closed by DxCx** 2017-11-26 06:38 UTC
