### ISSUE TITLE
List Returns only 1 title or none at all.

### ISSUE THREAD

**Issue by HatHeadNinja** [DxCx/plugin.video.9anime#221] opened 2018-04-22 04:39 UTC
Hello,

Firstly, thanks to those who created and maintain this plugin, it is my favorite Kodi plugin!

Perhaps something under the hood has changed at the underlying 9anime website as the plugin menus, which worked great earlier today, now no longer return the corresponding items (the only title I ever see is My Hero Academia 3)  EDIT: only title is One Piece, as below.

Same behavior with search return results.

Titles I have favorited via the plugin still good!

**Comment by XxkingkrowxX** [comment] 2018-04-22 05:37
Same here all tabs lead to single result "One Piece" for me though

**Comment by CNDVidel** [comment] 2018-04-22 08:24
I'm seeing the same thing on my end, too.

**Comment by Cockie** [comment] 2018-04-22 10:27
Same issue, everything is One Piece (even when using search, in which case One Piece shouldn't even be in the result). Makes it kind of impossible to watch anything else. :)

**Comment by Dobss7** [comment] 2018-04-22 10:40
Same issue. Unable to play any of the titles as well but I assume that's expected with the sorting issue

**Comment by romxuk** [comment] 2018-04-22 20:52
Same issue here too, Hope it gets sorted it is the only place I have found decent quality dubbed episodes of toriko

**Comment by GamingToad66** [comment] 2018-04-23 02:15
I did a bit of testing, the shows are coming up correctly but are being displayed under One Piece and are being broken up to one per page instead of the usual amount. I'm gonna try to see if I can figure anything else out, but I hope this helps get the issue fixed sooner.

**Comment by Dobss7** [comment] 2018-04-23 04:14
I noticed that too cause the other day on recently dubbed the first link called one piece came up with 2 episodes. Episode 2 and 3 and the only anime that really fits that is MHA but if you try to play the link you get an error

**Comment by JoshToshiro** [comment] 2018-04-23 04:46
Same issue here, was about to watch the new episode of My Hero Academia Season 3 but only one piece shows up.
On a side note however, I love this plugin and it’s my main source of entertainment. Thanks for all the hard work you put into it.

**Comment by jeremyjpj0916** [comment] 2018-04-23 04:54
Can confirm, Appears to be a bug, posting here in hopes we get some sort of notice when the dev figures out what rekt us.

**Comment by GitHubCaps** [comment] 2018-04-23 17:39
I can confirm that SwagOtaku's fix works on my end. Thanks

**Comment by ForTheLoveOfTech** [comment] 2018-04-23 20:03
I can confirm SwagOtaku's method works as well. If you want to use the add-on immediately you will have to update the code inside the add-on yourself. If not you will have to wait until a new zip or repository file is released.

**Comment by Randomdude707** [comment] 2018-04-23 20:37
If you don't mind me asking how do I do that

**Comment by andystyle09** [comment] 2018-04-23 20:46
Yes please I would also like to know the details and how to’s to do this fix. Thank you all!

**Comment by cbizzle14** [comment] 2018-04-23 20:56
Thanks for the answer ForTheLoveOfTech

**Comment by ForTheLoveOfTech** [comment] 2018-04-23 21:17
First you have to download the zip file onto your computer then extract it. Once you extract it you open the plugin.video.9anime-master folder then go to resources folder>then lib folder>then NineAnimeBrowser.py file. Once you open the NineAnimeBrowser.py file you just replace the lines of code that SwagOtaku mentioned and then save and close the file. Now you just replace the old NineAnimeBrowser.py file with the old new NineAnimeBrowser.py file you just edited back into the zip file you extracted the plugin.video.9anime-master folder from. Now you just load the zip file back on to whatever media device you use then reinstall the add-on and everything should work again as normal. It sounds like alot of steps but its not really that much to do if you know how to navigate a computer relatively well.

**Comment by ForTheLoveOfTech** [comment] 2018-04-23 21:24
No problem everyone. This is probably the best anime add-on available and I know those who use it often are probably anxiously waiting for a fix so they can get back to using it.

**Comment by ChaoticLag** [comment] 2018-04-23 21:28
still confused can this only be done on computer?

**Comment by ForTheLoveOfTech** [comment] 2018-04-23 21:37
If you know of some way to edit the code on which ever media you use then no, but I used a computer because it was easier for me and faster.

**Comment by Aguzy** [comment] 2018-04-23 22:17
I just downloaded the swagotaku zip file and then installed it from zip file and it's fixed the addon,  everything seems to be fixed doing it that way if people aren't confident changing code this way works.

**Comment by JoshToshiro** [comment] 2018-04-23 22:42
Can I use that same method on fire stick? 😅

**Comment by JoshToshiro** [comment] 2018-04-23 22:44
I’m not too confident about changing the code so I think I’ll stick to downloading it

**Comment by Randomdude707** [comment] 2018-04-23 23:09
So do I install on my firebrick will it still work

**Comment by Randomdude707** [comment] 2018-04-23 23:10
*firebrick

**Comment by Randomdude707** [comment] 2018-04-23 23:10
Hugh firestick

**Comment by ForTheLoveOfTech** [comment] 2018-04-23 23:11
If you install SwagOtaku's updated zip file that should solve your problems Randomdude707.

**Comment by Aguzy** [comment] 2018-04-23 23:27
@JoshToshiro if you aren't on a computer you may have to press on desktop version at the bottom of the screen and the option to download should appear then.

**Comment by isparkx1** [comment] 2018-04-23 23:48
Just did this 2 mins ago on my firestick, used downloader to download the fix via "https://github.com/SwagOtaku/plugin.video.9anime/archive/SwagOtaku-Plot.zip" and then went to kodi installed from zip file. pop up came up saying add on updated and it works perfectly now, long file now i know but it worked for me hope it does you anyone else on firestick

**Comment by JoshToshiro** [comment] 2018-04-23 23:50
@isparkx1 nice! Thanks for the tip, I’ll try it out

**Comment by player7000000** [comment] 2018-04-24 01:06
Hey guys it doesn't work for me on firestick at all. I guess I'll just wait for the release on the repository. Also, I've been adding my shows to my favorite list, and it's helped with this recent issue since I don't have search for my shows lol

**Comment by Randomdude707** [comment] 2018-04-24 01:12
Thank you all so much I'm so glad that I'm finally able to watch anime again

**Comment by jonedc** [comment] 2018-04-24 02:53
zip file works!!!!

**Comment by andystyle09** [comment] 2018-04-24 03:29
Just confirmed zip works perfectly fine on my fire stick doing the downloader method thank you everyone 🙏🏼

**Comment by JoshToshiro** [comment] 2018-04-24 03:40
Zip is working good for me also. Back in business! Thanks so much!! 🙏🏾🙏🏾 You guys are awesome.

**Comment by dokoab** [comment] 2018-04-24 08:32
Direct link to zip is this:
https://github.com/SwagOtaku/plugin.video.9anime/archive/SwagOtaku-Plot.zip

**Comment by JaeFr0st** [comment] 2018-04-24 19:55
Is 9anime down? I go on it and it takes forever to load and when it finally does load, its blank. Nothing is showing up.

**Comment by JaeFr0st** [comment] 2018-04-24 20:16
9ANIME is not working at all for me. All folders are empty. When I click on a folder like latest, newest, or genres and so on, it takes forever to load and when it finally does load it’s completely empty.

**Comment by JaeFr0st** [comment] 2018-04-24 20:38
@Aguzy you’re a legend. Well actually everyone on here is. Thanks for everyone’s help. That was so easy. Thank you all.

**Comment by jimboisit** [comment] 2018-04-24 21:42
anyone know how to update this on xbox

**Comment by cbizzle14** [comment] 2018-04-24 22:40
@jimboisit you'll have to use a USB drive.

**Comment by jimboisit** [comment] 2018-04-24 22:59
@cbizzle14 thank you so much i didnt know USBs work with kodi on xbox

**Comment by chrisupi007** [comment] 2018-04-25 03:25
I had the same issue and after installing SwagOtaku's fix, everything's working fine again. Thanx!

**Comment by DxCx** [comment] 2018-04-25 18:54
Thanks @SwagOtaku for the fix, it was merged!

**Closed by DxCx** 2018-04-25 18:54 UTC

**Comment by dokoab** [comment] 2018-04-26 06:45
@jimboisit to update on a box I upload the zip to htpps://uguu.se (a temp file host), shorten the link with goo.gl or bit.ly and write it down, then download it on my box through chrome web browser (Android edition).

Then you can install from zip in Kodi, it'll be in your Downloads folder

**Comment by jimboisit** [comment] 2018-04-27 02:54
@dokoab i was talking about the xbox one not an Android and i fixed it anyway but thank you
