### ISSUE TITLE
addon not working(KODI- Jarvis and krypton)

### ISSUE THREAD

**Issue by gooksta** [DxCx/plugin.video.9anime#89] opened 2017-07-03 04:16 UTC
So this is my first time trying to use this addon for kodi. I love the site generally so i figured there was probably an addon.

Currently running KODI on both jarvis and krypton, neither are working beyond the main page.

What I have currently tried:
uninstalling addon
uninstalling repo
reinstalling repo
reinstalling addon

tried both sites https://goo.gl/p9Lde0 & https://github.com/DxCx/plugin.video.9anime/archive/master.zip

repo/addon install without an issue. Just can't get into any subfolders it just error's out, on the page with:

Latest
Newest
Recent Subbed
Popular Subbed
Recent Dubbed
Popular Dubbed
Genres
Search

Says to check logs but there is no logs to actually check what the issue maybe, if anyone has any ideas of what I could do it would be appreciated.

**Comment by hoppler** [comment] 2017-07-03 06:23
see #88

**Comment by DxCx** [comment] 2017-07-03 06:35
Duplicate of #88

**Closed by DxCx** 2017-07-03 06:35 UTC
