### ISSUE TITLE
9anime error

### ISSUE THREAD

**Issue by anthony01235** [DxCx/plugin.video.9anime#349] opened 2018-08-26 03:06 UTC
each time i select any anime it give me a 9anime error 
i download the new update but still does it

**Comment by mattyyy12** [comment] 2018-08-26 03:07
App seems to be down, the website is working fine. Use another app till it’s updated like fireanime or watchnixtoon

**Comment by Jkrise** [comment] 2018-08-26 03:13
Skiing the same for me, was working like 45 minutes ago, but now, nothing. I have tried restarting my Kodi and the entire box it is on and nothing.

**Comment by JoshToshiro** [comment] 2018-08-26 03:13
Same here. Tried to watch the new episode of MHA but keeps giving me an error every time I click the anime or any anime rather. Updated it but no luck. This is happening on my firestick

**Comment by JoshToshiro** [comment] 2018-08-26 03:14
Restarted my firestick and uninstalled and installed 9anime but nothing.

**Comment by anthony01235** [comment] 2018-08-26 03:15
same here

**Comment by andystyle09** [comment] 2018-08-26 06:02
Same getting and error log notification. Was working fine 8/23/18

**Comment by Cayz181299** [comment] 2018-08-26 10:47
Same here can't open 9anime

**Comment by RexfelisLOC** [comment] 2018-08-26 12:45
They've gone back to changing their tokens again.  Funny thing is that their pages on a browser are failing their tokens too, so nothing loads.

**Comment by RexfelisLOC** [comment] 2018-08-26 12:53
They've also implemented CAPTCHA

https://www.reddit.com/r/9anime/comments/9adnse/about_missing_episode_list_login_feature_and/

**Comment by z89x23** [comment] 2018-08-26 14:34
I have the same problem

**Comment by RexfelisLOC** [comment] 2018-08-26 14:34
Process seems to be that you must first answer the CAPTCHA before using the tokens to make ajax calls.

**Comment by Jkrise** [comment] 2018-08-26 17:21
Will the captcha make it impossible to fix this?

**Comment by ruegnueg** [comment] 2018-08-26 19:47
Man i hate captchas really. In Browsers is use and pay 2captcha for that shit. couldnt they just ad pairing like normal people 😂

**Comment by ruegnueg** [comment] 2018-08-26 19:49
captcha usual mean i drop the whole site for good.

**Comment by JustAguyWhoLikesAnime** [comment] 2018-08-27 00:32
@Jkrise there may be a way around it as when I go on my ipad on the site I get no CAPTCHA and I can watch what I want

**Comment by JustAguyWhoLikesAnime** [comment] 2018-08-27 00:34
@RexfelisLOC  looks like it is a simple just click to load episodes so hopefully it can be fixed

**Comment by JustAguyWhoLikesAnime** [comment] 2018-08-27 01:29
@icpryde  they have to fix the addon hopefully they can

**Comment by RedNinjaX** [comment] 2018-08-27 01:42
Interesting. Somehow my website can still grab content from 9anime no problem. Don't know how this captcha issue applies to ajax

**Comment by Jkrise** [comment] 2018-08-27 02:29
@RedNinjaX d press your site can the video links too? I wonder if there is a useragentstring that causes the site to behave differently? I thought someone had said their iPad wasn't getting the captcha, if that is true and your system is not getting them either, we may be able to emulate a browser that gets detected as not supporting a captcha and bypass it that way?

Not that I have any clue how this works behind the scenes, just a thought I had.

**Comment by RexfelisLOC** [comment] 2018-08-27 02:42
The CAPTCHA only seems to appear for me the first time after cookies are cleared, so actually does not occur each show.

**Comment by JustAguyWhoLikesAnime** [comment] 2018-08-27 06:40
@RexfelisLOC  I was the one that said that but then I got one it seems to not be everytime most of the time I just need to push the button and no CAPTCHA  comes up

**Comment by ruegnueg** [comment] 2018-08-27 11:58
@ Mikedagreat90  its already said, because of the captchas.

**Comment by Mikedagreat90** [comment] 2018-08-27 12:27
No need for a dislike for a simple question is there? Still theres no answer as to when this issue will be fixed? I understand captcha is implemented for the website but addons work differently no?

**Comment by mattyyy12** [comment] 2018-08-27 12:32
@Mikedagreat90 I think you’re forgetting that this app is free, it’s up to the developer whether or not he will fix it now or next year. There is no ETA

**Comment by Mikedagreat90** [comment] 2018-08-27 12:42
I understand now thank you for the input. I need to mention that if i download the plugin i tried to look in the xml files and i noticed that there was a ww8 in it. Im talking about settings xml. I think its suppose to be ww9 instead. Im not sure if that has to do anything with it?

**Comment by mattyyy12** [comment] 2018-08-27 13:16
@Mikedagreat90 there is a possibility but nothing can be ruled out as of now. It could be related to the captcha, that or something completely differently. The developers here are very competent so I wouldn’t worry too much. It’ll get fixed very soon hopefully since he usually releases fixes ASAP

**Comment by dayv6880** [comment] 2018-08-27 14:43
If you really wanted to watch on 9anime and have a laptop or PC with HDMI port you could just connect to your TV and watch from the website.

**Comment by RedNinjaX** [comment] 2018-08-27 14:46
The issue is strictly a captcha issue in relation to the ajax request and we are currently in talks of what to do.

**Comment by Prometheusx-git** [comment] 2018-08-28 08:53
Maybe you could solve the captcha using the audio variant. 
Dowload the audio, play it in Kodi, make a Keyboard field, then let the user enter the words und paste it.
The problem i see is that the response is javascript processed before it can be pasted...

**Comment by ruegnueg** [comment] 2018-08-28 20:00
ill use mainly watchnix right now. but tried the newest fireanime apk, is it only me or is fireanime really that buggy?

**Comment by Osoreru9281** [comment] 2018-08-29 03:42
@ruegnueg mines really buggy too hasnt been loading in or just stuck on loading screen :c

**Comment by JustAguyWhoLikesAnime** [comment] 2018-08-29 04:05
@Osoreru9281 if you have a fire tv or something like that I may be able to help you

**Comment by Mikedagreat90** [comment] 2018-08-29 05:30
Just use Masterani redux. Really nice addon with clean interface.

**Comment by Osoreru9281** [comment] 2018-08-29 07:48
@justaguywholikesanime im on firestick, but is fire tv better? id have no problem upgrading if its worth it

**Comment by ruegnueg** [comment] 2018-08-29 07:56
watchnix. works good

**Comment by ruegnueg** [comment] 2018-08-29 07:59
Masterani redux huh? from which repo? seems to Have more than one. whats the benifit over watchnix?

**Comment by ruegnueg** [comment] 2018-08-29 08:05
uhhhh tried the Wilson repo, with Trakt Integration. sounds good.

**Comment by Mikedagreat90** [comment] 2018-08-29 08:55
Yep watchnix is inferior in every way if u ask me. Enjoy high quality content and clean interface with madterani😉

**Comment by ruegnueg** [comment] 2018-08-29 09:03
but there are some issues. well the Trakt login, die and strange behavior after adding an anime to list.... Well still, und a good one 👌 scraping fanart too 😉 mostly.

**Comment by ruegnueg** [comment] 2018-08-29 09:06
but its the first anime addon i could create a nice widget in Main Menu 😂

**Comment by Mikedagreat90** [comment] 2018-08-29 09:10
There u go im glad u like this addon! I just used 9anime as a backup for example if i cant get 1080p on masterani then i would give a shot using 9anime! Oh well guess we need to wait for a fix

**Comment by ruegnueg** [comment] 2018-08-29 09:15
everyone always forget its Bitrate that matters, more than Pixels 😂 4k with 1mbit looks worse than 720p sometimes.

**Comment by Mikedagreat90** [comment] 2018-08-29 09:34
I totally agree with u on this matter🙌

**Comment by ruegnueg** [comment] 2018-08-29 09:43
but hey i use netflix and prime. So i am not only a bad pirate 😂

**Comment by maveric69** [comment] 2018-08-30 14:17
9anime provides shows that masterani does not have and masterani has content 9anime does not. I use 9anime addon as my primary as it is more stable than masterani. Both have issues lately. I can't wait for 9anime to get fixed but until then I use masterani redux. Please fix this asap. I know you are doing your best. Thanks!

**Comment by Royster-77** [comment] 2018-08-30 22:10
Does make you wonder if 9anime are changing their website every so often on purpose to break the plugin...i mean we can watch anything without worrying about their annoying pop-ups or ads which they have to help pay for the site so they won't like us bypassing them xD

**Comment by Mikedagreat90** [comment] 2018-08-31 04:33
As of now il give it a try as well. Madterani redux is not working as well! Seriously is this an epidemic among anime addons😱?

**Comment by Mikedagreat90** [comment] 2018-08-31 06:28
Yep it does now! Thnx

**Comment by Shahav** [comment] 2018-08-31 07:32
Thanx for the zip file link to your anime repo. Was wondering:  If there
was any way i could get the add source file manager address cause i am
having issues on my end opening and extracting the zip file that i
downloaded. I do know why but don't want to mess with it right now; just a
girl who wants to watch my anime right now....  LOL

Sherry

**Comment by z89x23** [comment] 2018-08-31 08:15
Why unzip it ? Just click on install from zip

**Comment by 666jet** [comment] 2018-08-31 08:35
Could we maybe try using the fake site http://9anime.cloud/9anime but obviously advice against logging into that one

**Comment by doko-desuka** [comment] 2018-08-31 10:00
@Shahav I agree with @z89x23, the easiest way to install is to download the ZIP to your device, keep it as it is and then from within Kodi follow these instructions: https://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files  
Before you do that you need to enable "Unknown Sources" from your Settings > System > Add-ons screen in Kodi to be able to install any ZIPs that you get from the web.

Installing someone's repository is done in the same way, you need the ZIP of their repo files, install it from within Kodi, then go to "[Install from Repository](https://kodi.wiki/view/Add-on_manager#How_to_install_add-ons_from_a_repository)" and go to the one you just installed. It's in the video add-ons category.

**Comment by doko-desuka** [comment] 2018-08-31 10:04
And in the meantime you can also get Masterani Redux from Magicality's repo:  
https://wilsonmagic.github.io/repo/

**Comment by DxCx** [comment] 2018-09-01 19:15
Addon is deprecated, i am sick of fixing stuff that breaks so often..
i am working on a new solution thou, so stay tuned. :)

**Comment by ruegnueg** [comment] 2018-09-01 19:17
dude that's totally fine. 9anime are idiots just like kissanime. would do the same :-)

**Closed** 2018-09-01 19:18 UTC

**Comment by ruegnueg** [comment] 2018-09-01 20:30
Well we already have 2-3 good to great alternatives.

**Comment by Shahav** [comment] 2018-09-01 22:30
Sorry Doko-Desuka i guess there was a misunderstanding somehow on my part
but that was not the info. that was wanting.......😭😢  That is very basic
info. that every kodi user should know & am pretty well versed in
kodi.😵😆🌟✌

Sherry

**Comment by NDSiManTV** [comment] 2018-09-24 00:03
I am able to use the add-on again, as in looking at the episode list and playing back anime, but I don't know how much longer it will work.
